using Microsoft.EntityFrameworkCore.Migrations;

namespace TweetbookAPI.Migrations
{
    public partial class AutoGenerated_RefreshTokenKey : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
